USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS SOCCER_RECRUITMENT;
USE DATABASE SOCCER_RECRUITMENT;

CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_COMPETITIONS (
    payload VARIANT,
    extracted_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    source STRING,
    competition_code STRING,
    season STRING
);

CREATE TABLE IF NOT EXISTS RAW_TEAMS (
    team_id NUMBER,
    payload VARIANT,
    extracted_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    source STRING,
    competition_code STRING,
    season STRING
);

CREATE TABLE IF NOT EXISTS RAW_MATCHES (
    match_id NUMBER,
    payload VARIANT,
    extracted_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    source STRING,
    competition_code STRING,
    season STRING
);

CREATE TABLE IF NOT EXISTS RAW_STANDINGS (
    payload VARIANT,
    extracted_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    source STRING,
    competition_code STRING,
    season STRING
);

CREATE TABLE IF NOT EXISTS RAW_SCORERS (
    payload VARIANT,
    extracted_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    source STRING,
    competition_code STRING,
    season STRING
);
